### ISSUE TITLE
Styling: Components elements to tailwind

### ISSUE THREAD

**Issue by TaylorC19** [GamerTalk/Frontend#155]
(high effort) convert styling to use tailwind

- [x] dict-add
- [x] Checkbox
- [x] Dict-Checkbox
- [ ] Learning-checkbox
- [x] Scale
- [x] SubmitBtn

**Comment by TaylorC19** [comment]
@LakGillJPN I think I've done all the other ones, but the last one also uses the entry form CSS, so can you do it with your current ticket? It is once CSS class

**Comment by LakGillJPN** [comment]
> @LakGillJPN I think I've done all the other ones, but the last one also uses the entry form CSS, so can you do it with your current ticket? It is once CSS class

Sure, I'm working through the entry-form currently.

**Comment by TaylorC19** [comment]
Since you added a note for the learning box in your other ticket, I will be closing this ticket.
